### PR TITLE
Update for 23.12.0

### PR DESCRIPTION
**Pull request by smplayer-dev**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Please, also consider updating the runtime and base versions to _5.15-23.08_. Thanks! :-)

**Comment by smplayer-dev** [comment]
> Please, also consider updating the runtime and base versions to _5.15-23.08_. Thanks! :-)

I'm afraid ffmpeg fails to compile with that version.

**Comment by AsciiWolf** [comment]
You can use ffmpeg from the runtime. See [this](https://github.com/flathub/io.github.jliljebl.Flowblade/pull/31/files#diff-389bded4db94d829816b2673d52cdfa9c0a252ee75911bfc3483cdb1e569fb5fR31) as an example.

**Comment by smplayer-dev** [comment]
mplayer and smtube fail to compile as well.

**Comment by smplayer-dev** [comment]
mplayer fails when compiling its internal ffmpeg, if I use the ffmpeg from the sdk then it compiles but fails at runtime with signal 11.
So it seems the only way to build smplayer with 5.15-23.08 is by turning off mplayer and smtube.

**Comment by Erick555** [comment]
Theoretically you could patch them but dropping may be also good move for the future.

**Pull request merged**
