### PR TITLE
update to org.freedesktop.Platform 22.08, since 21.08 is end-of-life

### PR DESCRIPTION
**Pull request by TorrSamaho**
Title says it all. I briefly tested this change locally and it worked fine.

### CODE REVIEW

**Comment by TorrSamaho** [comment]
```
Cloning into '.'...
fatal: unable to access 'https://github.com/flathub/info.smplayer.SMPlayer/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
program finished with exit code 128
```
This does not seem to be a problem with the code, but rather a connection problem.

**Comment by Erick555** [comment]
you need to build it again

**Comment by TorrSamaho** [comment]
> you need to build it again

Is there a way to trigger another build without making code changes?

**Comment by Justinzobel** [comment]
bot, build

**Comment by TorrSamaho** [comment]
Thanks for triggering the rebuilt!

**Comment by Justinzobel** [comment]
No worries, just trying to do what I can to get apps off of EOL runtimes.

**Pull request merged**
